# ─────────────────────────────────────────────────────────────────────────────
# Stone Node Deployment Config
#
# Jeder [[node]] Block ist ein Server, zu dem deployed wird.
# ─────────────────────────────────────────────────────────────────────────────

[[node]]
name    = "server1"
host    = "100.90.28.68"
user    = "root"
port    = "22"
root    = "/opt/stone-node"
path    = "/opt/stone-node/target/release"
service = "stone-node"
bins    = "stone-setup stone-master"

[[node]]
name    = "VPSServer"
host    = "212.227.54.241"
user    = "root"
port    = "22"
root    = "/home"
path    = "/home"
service = "stone-node"
bins    = "stone-setup stone-master"

[[node]]
name    = "VPS2"
host    = "69.48.200.255"
user    = "root"
port    = "22"
root    = "/home"
path    = "/home"
service = "stone-node"
bins    = "stone-setup stone-master"

[[node]]
name    = "server2"
host    = "10.1.128.189"
user    = "root"
port    = "22"
path    = "/home"
service = "stone-node"
bins    = "stone-setup stone-master"
